version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      - LIMITE_REQUISICOES_TOKEN=10
      - LIMITE_REQUISICOES_IP=10
      - TEMPO=30
  redis:
    image: redis:latest
    container_name: rate-limiter-redis
    ports:
      - 6379:6379