version: '3.8'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - ENV=production # Adicione variáveis de ambiente conforme necessário
  redis:
    image: redis:latest
    container_name: rate-limiter-redis
    ports:
      - 6379:6379
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/app
    working_dir: /app